import uuid
from datetime import datetime

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    String,
)
from sqlalchemy.dialects.postgresql import (
    JSONB,
    UUID,
)
from sqlalchemy.orm import (
    Mapped,
    mapped_column,
)

from app.db.base import Base
from app.utils.time import utc_now


class AuditEvent(Base):
    """
    Append-only application audit record.

    Application code should create audit events through
    app.services.audit.service.record_audit_event().

    Updating/deleting historical audit rows is intentionally
    not part of the normal application API.

    Production immutability must additionally be enforced
    through database privileges and/or external centralized
    log shipping.
    """

    __tablename__ = "audit_events"

    __table_args__ = (
        Index(
            "ix_audit_events_admin_session_created",
            "admin_session_id",
            "created_at",
        ),
        Index(
            "ix_audit_events_request_id_created",
            "request_id",
            "created_at",
        ),
    )

    # ========================================================
    # EVENT IDENTITY
    # ========================================================

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    # ========================================================
    # ACTOR
    # ========================================================

    actor_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )

    actor_id: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        index=True,
    )

    # ========================================================
    # ADMIN SESSION CONTEXT
    # ========================================================

    #
    # Intentionally no FK to admin_sessions.
    #
    # Audit history must survive session cleanup and should
    # not depend on the continued existence of operational
    # authentication/session rows.
    #
    admin_session_id: Mapped[
        uuid.UUID | None
    ] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
        index=True,
    )

    # ========================================================
    # VERIFICATION RESOURCE
    # ========================================================

    verification_request_id: Mapped[
        uuid.UUID | None
    ] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "verification_requests.id",
            ondelete="SET NULL",
        ),
        nullable=True,
        index=True,
    )

    # ========================================================
    # ACTION / OUTCOME
    # ========================================================

    action: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
    )

    #
    # Success/failure/denied/etc.
    #
    # Existing callers automatically retain "success" unless
    # they explicitly record another outcome.
    #
    outcome: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        default="success",
        index=True,
    )

    # ========================================================
    # REQUEST / CORRELATION CONTEXT
    # ========================================================

    #
    # Correlation/request ID generated by the HTTP boundary.
    #
    # String rather than UUID because request-ID formats may
    # differ between reverse proxies and the application.
    #
    request_id: Mapped[str | None] = mapped_column(
        String(128),
        nullable=True,
        index=True,
    )

    ip_address: Mapped[str | None] = mapped_column(
        String(64),
        nullable=True,
    )

    user_agent: Mapped[str | None] = mapped_column(
        String(512),
        nullable=True,
    )

    # ========================================================
    # EXTENSIBLE SECURITY / RESOURCE CONTEXT
    # ========================================================

    metadata_json: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
    )

    # ========================================================
    # TIMESTAMP
    # ========================================================

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        index=True,
    )