"""harden mobile capture sessions

Revision ID: 0033110f0e48
Revises: 4a149b8358cf
Create Date: 2026-08-28 04:00:55.542505

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '0033110f0e48'
down_revision: str | Sequence[str] | None = '4a149b8358cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
