"""add discord avatar snapshot

Revision ID: 06e355d22e69
Revises: 90ac90991d19
Create Date: 2026-08-26 23:58:09.402326

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '06e355d22e69'
down_revision: str | Sequence[str] | None = '90ac90991d19'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_requests', sa.Column('discord_avatar_hash_snapshot', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_requests', 'discord_avatar_hash_snapshot')
    # ### end Alembic commands ###
