"""sync mobile capture session schema

Revision ID: 24e419fa1333
Revises: 0033110f0e48
Create Date: 2026-08-30 02:41:01.550213

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '24e419fa1333'
down_revision: str | Sequence[str] | None = '0033110f0e48'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobile_capture_sessions', sa.Column('mobile_session_token_hash', sa.String(length=64), nullable=True))
    op.add_column('mobile_capture_sessions', sa.Column('exchange_consumed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mobile_capture_sessions', sa.Column('mobile_session_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_mobile_capture_sessions_exchange_consumed_at'), 'mobile_capture_sessions', ['exchange_consumed_at'], unique=False)
    op.create_index(op.f('ix_mobile_capture_sessions_mobile_session_expires_at'), 'mobile_capture_sessions', ['mobile_session_expires_at'], unique=False)
    op.create_index(op.f('ix_mobile_capture_sessions_mobile_session_token_hash'), 'mobile_capture_sessions', ['mobile_session_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mobile_capture_sessions_mobile_session_token_hash'), table_name='mobile_capture_sessions')
    op.drop_index(op.f('ix_mobile_capture_sessions_mobile_session_expires_at'), table_name='mobile_capture_sessions')
    op.drop_index(op.f('ix_mobile_capture_sessions_exchange_consumed_at'), table_name='mobile_capture_sessions')
    op.drop_column('mobile_capture_sessions', 'mobile_session_expires_at')
    op.drop_column('mobile_capture_sessions', 'exchange_consumed_at')
    op.drop_column('mobile_capture_sessions', 'mobile_session_token_hash')
    # ### end Alembic commands ###
