"""add admin auth subject

Revision ID: 2dacc6c246c5
Revises: 77ed426d55f8
Create Date: 2026-08-25 01:04:25.302335

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2dacc6c246c5'
down_revision: str | Sequence[str] | None = '77ed426d55f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('auth_subject', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_admins_auth_subject'), 'admins', ['auth_subject'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_auth_subject'), table_name='admins')
    op.drop_column('admins', 'auth_subject')
    # ### end Alembic commands ###
