"""link evidence to mobile capture

Revision ID: 4a149b8358cf
Revises: 8e1d2ad160aa
Create Date: 2026-08-28 03:08:52.597072

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4a149b8358cf'
down_revision: str | Sequence[str] | None = '8e1d2ad160aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_objects', sa.Column('mobile_capture_session_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_evidence_objects_mobile_capture_session_id'), 'evidence_objects', ['mobile_capture_session_id'], unique=False)
    op.create_foreign_key(None, 'evidence_objects', 'mobile_capture_sessions', ['mobile_capture_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence_objects', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_objects_mobile_capture_session_id'), table_name='evidence_objects')
    op.drop_column('evidence_objects', 'mobile_capture_session_id')
    # ### end Alembic commands ###
