"""add verification entry contexts

Revision ID: 6891ad85f6ab
Revises: 06e355d22e69
Create Date: 2026-08-27 00:44:42.103640

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6891ad85f6ab'
down_revision: str | Sequence[str] | None = '06e355d22e69'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_entry_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('context_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_entry_contexts_context_token_hash'), 'verification_entry_contexts', ['context_token_hash'], unique=True)
    op.create_index(op.f('ix_verification_entry_contexts_expires_at'), 'verification_entry_contexts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_verification_entry_contexts_verification_request_id'), 'verification_entry_contexts', ['verification_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_entry_contexts_verification_request_id'), table_name='verification_entry_contexts')
    op.drop_index(op.f('ix_verification_entry_contexts_expires_at'), table_name='verification_entry_contexts')
    op.drop_index(op.f('ix_verification_entry_contexts_context_token_hash'), table_name='verification_entry_contexts')
    op.drop_table('verification_entry_contexts')
    # ### end Alembic commands ###
