"""initial verification schema

Revision ID: 77ed426d55f8
Revises: 
Create Date: 2026-08-24 21:01:30.409612

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77ed426d55f8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('reviewer', 'admin', 'super_admin', name='admin_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_role'), 'admins', ['role'], unique=False)
    op.create_table('verification_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assigned_discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_username_snapshot', sa.String(length=100), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'in_review', 'more_info', 'approved', 'rejected', 'expired', 'revoked', name='verification_status'), nullable=False),
    sa.Column('required_evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('max_submissions', sa.Integer(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('assigned_reviewer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queue_entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_grant_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_reviewer_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_requests_assigned_discord_user_id'), 'verification_requests', ['assigned_discord_user_id'], unique=False)
    op.create_index(op.f('ix_verification_requests_assigned_reviewer_id'), 'verification_requests', ['assigned_reviewer_id'], unique=False)
    op.create_index(op.f('ix_verification_requests_created_by_admin_id'), 'verification_requests', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_verification_requests_expires_at'), 'verification_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_verification_requests_last_activity_at'), 'verification_requests', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_verification_requests_queue_entered_at'), 'verification_requests', ['queue_entered_at'], unique=False)
    op.create_index(op.f('ix_verification_requests_status'), 'verification_requests', ['status'], unique=False)
    op.create_index(op.f('ix_verification_requests_token_hash'), 'verification_requests', ['token_hash'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('verification_request_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_type'), 'audit_events', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_verification_request_id'), 'audit_events', ['verification_request_id'], unique=False)
    op.create_table('discord_access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('not_issued', 'issued', 'consumed', 'expired', 'revoked', name='access_grant_status'), nullable=False),
    sa.Column('invite_reference', sa.String(length=512), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_access_grants_discord_user_id'), 'discord_access_grants', ['discord_user_id'], unique=False)
    op.create_index(op.f('ix_discord_access_grants_expires_at'), 'discord_access_grants', ['expires_at'], unique=False)
    op.create_index(op.f('ix_discord_access_grants_status'), 'discord_access_grants', ['status'], unique=False)
    op.create_index(op.f('ix_discord_access_grants_verification_request_id'), 'discord_access_grants', ['verification_request_id'], unique=True)
    op.create_table('verification_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_admin_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_decisions_reviewer_admin_id'), 'verification_decisions', ['reviewer_admin_id'], unique=False)
    op.create_index(op.f('ix_verification_decisions_verification_request_id'), 'verification_decisions', ['verification_request_id'], unique=False)
    op.create_table('verification_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age_result', sa.String(length=50), nullable=True),
    sa.Column('issuing_country', sa.String(length=2), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('evidence_object_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consent_confirmed', sa.Boolean(), nullable=False),
    sa.Column('accuracy_confirmed', sa.Boolean(), nullable=False),
    sa.Column('client_risk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_submissions_verification_request_id'), 'verification_submissions', ['verification_request_id'], unique=False)
    op.create_table('evidence_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('verification_submission_id', sa.UUID(), nullable=True),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('is_temporary', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_submission_id'], ['verification_submissions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_evidence_objects_deleted_at'), 'evidence_objects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_evidence_objects_expires_at'), 'evidence_objects', ['expires_at'], unique=False)
    op.create_index(op.f('ix_evidence_objects_is_temporary'), 'evidence_objects', ['is_temporary'], unique=False)
    op.create_index(op.f('ix_evidence_objects_verification_request_id'), 'evidence_objects', ['verification_request_id'], unique=False)
    op.create_index(op.f('ix_evidence_objects_verification_submission_id'), 'evidence_objects', ['verification_submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_objects_verification_submission_id'), table_name='evidence_objects')
    op.drop_index(op.f('ix_evidence_objects_verification_request_id'), table_name='evidence_objects')
    op.drop_index(op.f('ix_evidence_objects_is_temporary'), table_name='evidence_objects')
    op.drop_index(op.f('ix_evidence_objects_expires_at'), table_name='evidence_objects')
    op.drop_index(op.f('ix_evidence_objects_deleted_at'), table_name='evidence_objects')
    op.drop_table('evidence_objects')
    op.drop_index(op.f('ix_verification_submissions_verification_request_id'), table_name='verification_submissions')
    op.drop_table('verification_submissions')
    op.drop_index(op.f('ix_verification_decisions_verification_request_id'), table_name='verification_decisions')
    op.drop_index(op.f('ix_verification_decisions_reviewer_admin_id'), table_name='verification_decisions')
    op.drop_table('verification_decisions')
    op.drop_index(op.f('ix_discord_access_grants_verification_request_id'), table_name='discord_access_grants')
    op.drop_index(op.f('ix_discord_access_grants_status'), table_name='discord_access_grants')
    op.drop_index(op.f('ix_discord_access_grants_expires_at'), table_name='discord_access_grants')
    op.drop_index(op.f('ix_discord_access_grants_discord_user_id'), table_name='discord_access_grants')
    op.drop_table('discord_access_grants')
    op.drop_index(op.f('ix_audit_events_verification_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_verification_requests_token_hash'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_status'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_queue_entered_at'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_last_activity_at'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_expires_at'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_created_by_admin_id'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_assigned_reviewer_id'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_assigned_discord_user_id'), table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_index(op.f('ix_admins_role'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
