"""add mobile capture sessions

Revision ID: 8e1d2ad160aa
Revises: 6891ad85f6ab
Create Date: 2026-08-28 01:56:21.002350

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e1d2ad160aa'
down_revision: str | Sequence[str] | None = '6891ad85f6ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_capture_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('verification_session_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_session_id'], ['verification_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_capture_sessions_expires_at'), 'mobile_capture_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_mobile_capture_sessions_status'), 'mobile_capture_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_mobile_capture_sessions_token_hash'), 'mobile_capture_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_mobile_capture_sessions_verification_request_id'), 'mobile_capture_sessions', ['verification_request_id'], unique=False)
    op.create_index(op.f('ix_mobile_capture_sessions_verification_session_id'), 'mobile_capture_sessions', ['verification_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mobile_capture_sessions_verification_session_id'), table_name='mobile_capture_sessions')
    op.drop_index(op.f('ix_mobile_capture_sessions_verification_request_id'), table_name='mobile_capture_sessions')
    op.drop_index(op.f('ix_mobile_capture_sessions_token_hash'), table_name='mobile_capture_sessions')
    op.drop_index(op.f('ix_mobile_capture_sessions_status'), table_name='mobile_capture_sessions')
    op.drop_index(op.f('ix_mobile_capture_sessions_expires_at'), table_name='mobile_capture_sessions')
    op.drop_table('mobile_capture_sessions')
    # ### end Alembic commands ###
