"""complete backend data model

Revision ID: 90ac90991d19
Revises: f6c098e9cc11
Create Date: 2026-08-26 00:53:46.904763

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '90ac90991d19'
down_revision: str | Sequence[str] | None = 'f6c098e9cc11'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('raw_evidence_retention_days', sa.Integer(), nullable=False),
    sa.Column('temporary_upload_retention_minutes', sa.Integer(), nullable=False),
    sa.Column('retain_verification_result', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_retention_policies_is_default'), 'retention_policies', ['is_default'], unique=False)
    op.create_table('system_job_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_job_runs_job_name'), 'system_job_runs', ['job_name'], unique=False)
    op.create_index(op.f('ix_system_job_runs_status'), 'system_job_runs', ['status'], unique=False)
    op.create_table('admin_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notes_admin_id'), 'admin_notes', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_notes_verification_request_id'), 'admin_notes', ['verification_request_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('eligibility_result', sa.String(length=100), nullable=True),
    sa.Column('reviewer_admin_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_discord_user_id'), 'verification_results', ['discord_user_id'], unique=False)
    op.create_index(op.f('ix_verification_results_verification_request_id'), 'verification_results', ['verification_request_id'], unique=True)
    op.create_check_constraint('ck_access_grant_expiry_after_issue', 'discord_access_grants', 'expires_at IS NULL OR issued_at IS NULL OR expires_at > issued_at')
    op.add_column('evidence_objects', sa.Column('deletion_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evidence_objects', sa.Column('deletion_reason', sa.String(length=255), nullable=True))
    op.add_column('evidence_objects', sa.Column('deleted_by_admin_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_evidence_objects_deletion_due_at'), 'evidence_objects', ['deletion_due_at'], unique=False)
    op.create_foreign_key(None, 'evidence_objects', 'admins', ['deleted_by_admin_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('ck_evidence_size_positive', 'evidence_objects', 'size_bytes > 0')
    op.create_check_constraint('ck_verification_max_submissions_positive', 'verification_requests', 'max_submissions >= 1')
    op.create_check_constraint('ck_verification_submission_count_limit', 'verification_requests', 'submission_count <= max_submissions')
    op.create_check_constraint('ck_verification_submission_count_nonnegative', 'verification_requests', 'submission_count >= 0')
    op.create_check_constraint('ck_submission_accuracy_required', 'verification_submissions', 'accuracy_confirmed = true')
    op.create_check_constraint('ck_submission_consent_required', 'verification_submissions', 'consent_confirmed = true')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_submission_consent_required', 'verification_submissions', type_='check')
    op.drop_constraint('ck_submission_accuracy_required', 'verification_submissions', type_='check')
    op.drop_constraint('ck_verification_submission_count_nonnegative', 'verification_requests', type_='check')
    op.drop_constraint('ck_verification_submission_count_limit', 'verification_requests', type_='check')
    op.drop_constraint('ck_verification_max_submissions_positive', 'verification_requests', type_='check')
    op.drop_constraint('ck_evidence_size_positive', 'evidence_objects', type_='check')
    op.drop_constraint(None, 'evidence_objects', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_objects_deletion_due_at'), table_name='evidence_objects')
    op.drop_column('evidence_objects', 'deleted_by_admin_id')
    op.drop_column('evidence_objects', 'deletion_reason')
    op.drop_column('evidence_objects', 'deletion_due_at')
    op.drop_constraint('ck_access_grant_expiry_after_issue', 'discord_access_grants', type_='check')
    op.drop_index(op.f('ix_verification_results_verification_request_id'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_discord_user_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_admin_notes_verification_request_id'), table_name='admin_notes')
    op.drop_index(op.f('ix_admin_notes_admin_id'), table_name='admin_notes')
    op.drop_table('admin_notes')
    op.drop_index(op.f('ix_system_job_runs_status'), table_name='system_job_runs')
    op.drop_index(op.f('ix_system_job_runs_job_name'), table_name='system_job_runs')
    op.drop_table('system_job_runs')
    op.drop_index(op.f('ix_retention_policies_is_default'), table_name='retention_policies')
    op.drop_table('retention_policies')
    # ### end Alembic commands ###
