"""add admin invitations

Revision ID: ccaae55f6a36
Revises: 8a6bf45b484d
Create Date: 2026-09-03 15:31:15.942027

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccaae55f6a36'
down_revision: str | Sequence[str] | None = '8a6bf45b484d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column("role",postgresql.ENUM("reviewer","admin","super_admin",name="admin_role", create_type=False,),nullable=False,),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by_admin_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_admin_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['accepted_admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by_admin_id'], ['admins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by_admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_invitations_accepted_admin_id'), 'admin_invitations', ['accepted_admin_id'], unique=False)
    op.create_index(op.f('ix_admin_invitations_accepted_at'), 'admin_invitations', ['accepted_at'], unique=False)
    op.create_index(op.f('ix_admin_invitations_email'), 'admin_invitations', ['email'], unique=False)
    op.create_index('ix_admin_invitations_email_state', 'admin_invitations', ['email', 'accepted_at', 'revoked_at', 'expires_at'], unique=False)
    op.create_index(op.f('ix_admin_invitations_expires_at'), 'admin_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_admin_invitations_invited_by_admin_id'), 'admin_invitations', ['invited_by_admin_id'], unique=False)
    op.create_index('ix_admin_invitations_inviter_created', 'admin_invitations', ['invited_by_admin_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_admin_invitations_revoked_at'), 'admin_invitations', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_admin_invitations_revoked_by_admin_id'), 'admin_invitations', ['revoked_by_admin_id'], unique=False)
    op.create_index(op.f('ix_admin_invitations_role'), 'admin_invitations', ['role'], unique=False)
    op.create_index(op.f('ix_admin_invitations_token_hash'), 'admin_invitations', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_invitations_token_hash'), table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_role'), table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_revoked_by_admin_id'), table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_revoked_at'), table_name='admin_invitations')
    op.drop_index('ix_admin_invitations_inviter_created', table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_invited_by_admin_id'), table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_expires_at'), table_name='admin_invitations')
    op.drop_index('ix_admin_invitations_email_state', table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_email'), table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_accepted_at'), table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_accepted_admin_id'), table_name='admin_invitations')
    op.drop_table('admin_invitations')
    # ### end Alembic commands ###
