"""add discord oauth and verification sessions

Revision ID: f51bc7ffc54e
Revises: 2dacc6c246c5
Create Date: 2026-08-25 01:49:02.652553

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f51bc7ffc54e'
down_revision: str | Sequence[str] | None = '2dacc6c246c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_oauth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_oauth_states_consumed_at'), 'discord_oauth_states', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_discord_oauth_states_expires_at'), 'discord_oauth_states', ['expires_at'], unique=False)
    op.create_index(op.f('ix_discord_oauth_states_state_hash'), 'discord_oauth_states', ['state_hash'], unique=True)
    op.create_index(op.f('ix_discord_oauth_states_verification_request_id'), 'discord_oauth_states', ['verification_request_id'], unique=False)
    op.create_table('verification_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_sessions_discord_user_id'), 'verification_sessions', ['discord_user_id'], unique=False)
    op.create_index(op.f('ix_verification_sessions_expires_at'), 'verification_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_verification_sessions_revoked_at'), 'verification_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_verification_sessions_session_token_hash'), 'verification_sessions', ['session_token_hash'], unique=True)
    op.create_index(op.f('ix_verification_sessions_verification_request_id'), 'verification_sessions', ['verification_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_sessions_verification_request_id'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_session_token_hash'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_revoked_at'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_expires_at'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_discord_user_id'), table_name='verification_sessions')
    op.drop_table('verification_sessions')
    op.drop_index(op.f('ix_discord_oauth_states_verification_request_id'), table_name='discord_oauth_states')
    op.drop_index(op.f('ix_discord_oauth_states_state_hash'), table_name='discord_oauth_states')
    op.drop_index(op.f('ix_discord_oauth_states_expires_at'), table_name='discord_oauth_states')
    op.drop_index(op.f('ix_discord_oauth_states_consumed_at'), table_name='discord_oauth_states')
    op.drop_table('discord_oauth_states')
    # ### end Alembic commands ###
