from __future__ import annotations

from collections.abc import Mapping
from datetime import UTC, datetime
from typing import Annotated, Any
from uuid import UUID

from fastapi import (
    APIRouter,
    Cookie,
    Depends,
    Header,
    HTTPException,
    Request,
    Response,
    status,
)
from fastapi.security import (
    HTTPAuthorizationCredentials,
    HTTPBearer,
)
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.constants import (
    ActorType,
    AuditAction,
)
from app.db.models.admin import Admin
from app.db.session import get_db_session
from app.services.admin.auth import (
    AdminAuthenticationError,
    decode_admin_step_up_token,
    decode_admin_token,
    get_admin_for_identity,
)
from app.services.admin.session_service import (
    AdminSessionError,
    CreatedAdminSession,
    InvalidAdminSessionError,
    create_admin_session,
    get_admin_csrf_cookie_name,
    get_admin_session_cookie_name,
    get_valid_admin_session,
    revoke_admin_session,
    revoke_admin_session_by_id,
    rotate_admin_csrf_token,
    rotate_admin_session,
    validate_admin_session_csrf,
)
from app.services.audit.service import (
    record_audit_event,
)

# ============================================================
# ROUTER
# ============================================================


router = APIRouter(
    prefix="/auth",
    tags=["admin-auth"],
)


# ============================================================
# FASTAPI DEPENDENCIES
# ============================================================


_bearer = HTTPBearer(
    auto_error=False,
)

BearerCredentials = Annotated[
    HTTPAuthorizationCredentials | None,
    Depends(_bearer),
]

DatabaseSession = Annotated[
    AsyncSession,
    Depends(get_db_session),
]


# ============================================================
# HELPERS
# ============================================================


def _is_production() -> bool:
    return (
        str(settings.app_environment)
        .strip()
        .lower()
        == "production"
    )


def _client_ip(
    request: Request,
) -> str | None:
    """
    Use the direct socket peer address.

    X-Forwarded-For is intentionally not trusted here.
    Production proxy trust must be configured explicitly at
    the deployment boundary.
    """

    if request.client is None:
        return None

    return request.client.host


def _request_id(
    request: Request,
) -> str | None:
    """
    Return the trusted request correlation ID generated by
    RequestContextMiddleware.

    Do not accept a client-supplied request ID here.
    """

    value = getattr(
        request.state,
        "request_id",
        None,
    )

    if not isinstance(
        value,
        str,
    ):
        return None

    normalized = (
        value.strip()
    )

    return normalized or None


def _user_agent(
    request: Request,
) -> str | None:
    return request.headers.get(
        "user-agent"
    )


async def _record_denied_auth_event(
    db: AsyncSession,
    *,
    request: Request,
    action: AuditAction,
    reason: str,
    admin: Admin | None = None,
    admin_session_id: UUID | None = None,
    metadata: Mapping[
        str,
        Any,
    ]
    | None = None,
) -> None:
    """
    Persist an authentication/security denial after the caller
    has rolled back the failed protected operation.

    Authentication credentials, session tokens, CSRF tokens,
    identity assertions and other secrets must never be placed
    in audit metadata.
    """

    event_metadata: dict[
        str,
        Any,
    ] = {
        "reason": reason,
    }

    if metadata is not None:
        event_metadata.update(
            dict(metadata)
        )

    await record_audit_event(
        db,
        actor_type=(
            ActorType.ADMIN.value
            if admin is not None
            else ActorType.SYSTEM.value
        ),
        actor_id=(
            str(admin.id)
            if admin is not None
            else None
        ),
        action=action.value,
        metadata=event_metadata,
        ip_address=_client_ip(
            request
        ),
        admin_session_id=(
            admin_session_id
        ),
        request_id=_request_id(
            request
        ),
        user_agent=_user_agent(
            request
        ),
        outcome="failure",
    )

    await db.commit()


async def _persist_invalid_admin_session(
    db: AsyncSession,
    *,
    request: Request,
    exc: InvalidAdminSessionError,
) -> None:
    """
    Persist automatic administrator-session invalidation after
    the failed validation transaction has been rolled back.

    Revocation and the corresponding audit event are committed
    atomically.

    Only safe persistent identifiers and reason codes from the
    validation exception are used. Raw session credentials are
    never logged or persisted here.
    """

    if not exc.requires_revocation:
        return

    if (
        exc.admin_id is None
        or exc.admin_session_id is None
    ):
        return

    reason = (
        exc.reason
        or "security_state_changed"
    )

    await revoke_admin_session_by_id(
        db,
        admin_session_id=(
            exc.admin_session_id
        ),
        admin_id=(
            exc.admin_id
        ),
        reason=reason,
    )

    if reason == "absolute_expiry":
        action = (
            AuditAction
            .ADMIN_SESSION_EXPIRED
        )

    elif reason == "idle_timeout":
        action = (
            AuditAction
            .ADMIN_SESSION_IDLE_EXPIRED
        )

    else:
        action = (
            AuditAction
            .ADMIN_SESSION_SECURITY_INVALIDATED
        )

    await record_audit_event(
        db,
        actor_type=ActorType.ADMIN.value,
        actor_id=str(
            exc.admin_id
        ),
        action=action.value,
        metadata={
            "reason": reason,
        },
        ip_address=_client_ip(
            request
        ),
        admin_session_id=(
            exc.admin_session_id
        ),
        request_id=_request_id(
            request
        ),
        user_agent=_user_agent(
            request
        ),
        outcome="failure",
    )

    await db.commit()


def _set_admin_cookies(
    response: Response,
    *,
    created: CreatedAdminSession,
) -> None:
    """
    Set the server-managed authentication cookie and the
    separate browser-readable CSRF cookie.
    """

    secure = bool(
        settings.cookie_secure
    )

    if _is_production():
        secure = True

    session_cookie_name = (
        get_admin_session_cookie_name()
    )

    csrf_cookie_name = (
        get_admin_csrf_cookie_name()
    )

    # --------------------------------------------------------
    # Authentication credential
    # --------------------------------------------------------
    #
    # Raw administrator session token:
    #
    # - HttpOnly
    # - Secure in production
    # - SameSite=Lax
    # - Path=/
    # - no Domain
    #
    # The raw value is never stored in PostgreSQL.
    #

    response.set_cookie(
        key=session_cookie_name,
        value=created.raw_token,
        max_age=(
            settings
            .admin_session_absolute_lifetime_seconds
        ),
        httponly=True,
        secure=secure,
        samesite="lax",
        path="/",
    )

    # --------------------------------------------------------
    # CSRF credential
    # --------------------------------------------------------
    #
    # This value is intentionally readable by frontend
    # JavaScript because the frontend must echo it in the
    # X-Admin-CSRF-Token header.
    #
    # It is NOT an authentication credential.
    #

    response.set_cookie(
        key=csrf_cookie_name,
        value=created.csrf_token,
        max_age=(
            settings
            .admin_session_absolute_lifetime_seconds
        ),
        httponly=False,
        secure=secure,
        samesite="lax",
        path="/",
    )


def _clear_admin_cookies(
    response: Response,
) -> None:
    """
    Remove both administrator browser cookies.
    """

    secure = bool(
        settings.cookie_secure
    )

    if _is_production():
        secure = True

    response.delete_cookie(
        key=(
            get_admin_session_cookie_name()
        ),
        path="/",
        secure=secure,
        httponly=True,
        samesite="lax",
    )

    response.delete_cookie(
        key=(
            get_admin_csrf_cookie_name()
        ),
        path="/",
        secure=secure,
        httponly=False,
        samesite="lax",
    )


def _admin_payload(
    admin: Admin,
) -> dict[str, object]:
    """
    Safe administrator representation returned to the
    authenticated frontend.

    Do not expose auth_subject or authentication secrets.
    """

    return {
        "id": str(admin.id),
        "email": admin.email,
        "display_name": (
            admin.display_name
        ),
        "role": admin.role.value,
    }


# ============================================================
# CREATE SERVER-MANAGED SESSION
# ============================================================


@router.post(
    "/session",
    status_code=(
        status.HTTP_201_CREATED
    ),
)
async def establish_admin_session(
    request: Request,
    response: Response,
    db: DatabaseSession,
    credentials: BearerCredentials,
    cloudflare_access_assertion: Annotated[
        str | None,
        Header(
            alias=(
                "Cf-Access-Jwt-Assertion"
            ),
        ),
    ] = None,
) -> dict[str, object]:
    """
    Exchange an externally authenticated administrator
    identity for a BAKABOOST server-managed session.

    Production authentication requires a cryptographically
    validated Cloudflare Access application JWT supplied in
    Cf-Access-Jwt-Assertion.

    The Authorization Bearer mechanism is accepted only by
    the explicitly enabled local-development authentication
    mode.

    External authentication alone never grants local
    administrator authorization. The immutable external
    subject must match an explicitly provisioned and active
    local Admin row.

    Ordinary Cloudflare Access application JWTs do not prove
    that a fresh MFA ceremony occurred at session creation.

    Therefore this endpoint creates only baseline local
    administrator assurance. Sensitive operations remain
    fail-closed until the dedicated step-up flow succeeds.
    """

    environment = (
        str(settings.app_environment)
        .strip()
        .lower()
    )

    development_auth = (
        environment == "development"
        and settings
        .dev_admin_auth_enabled
    )

    raw_assertion: str | None = None
    auth_method: str

    # --------------------------------------------------------
    # Resolve external authentication assertion
    # --------------------------------------------------------

    if development_auth:
        if credentials is not None:
            candidate = (
                credentials
                .credentials
                .strip()
            )

            if candidate:
                raw_assertion = (
                    candidate
                )

        auth_method = "development"

        if raw_assertion is None:
            await (
                _record_denied_auth_event(
                    db,
                    request=request,
                    action=(
                        AuditAction
                        .ADMIN_AUTH_DENIED
                    ),
                    reason=(
                        "missing_development_"
                        "credentials"
                    ),
                )
            )

            raise HTTPException(
                status_code=(
                    status
                    .HTTP_401_UNAUTHORIZED
                ),
                detail=(
                    "Authentication required."
                ),
                headers={
                    "WWW-Authenticate": (
                        "Bearer"
                    ),
                },
            )

    else:
        if isinstance(
            cloudflare_access_assertion,
            str,
        ):
            candidate = (
                cloudflare_access_assertion
                .strip()
            )

            if candidate:
                raw_assertion = (
                    candidate
                )

        auth_method = (
            "cloudflare_access"
        )

        if raw_assertion is None:
            await (
                _record_denied_auth_event(
                    db,
                    request=request,
                    action=(
                        AuditAction
                        .ADMIN_AUTH_DENIED
                    ),
                    reason=(
                        "missing_cloudflare_"
                        "access_assertion"
                    ),
                )
            )

            raise HTTPException(
                status_code=(
                    status
                    .HTTP_401_UNAUTHORIZED
                ),
                detail=(
                    "Authentication required."
                ),
            )

    admin: Admin | None = None
    created: (
        CreatedAdminSession
        | None
    ) = None

    try:
        # ----------------------------------------------------
        # Cryptographically verify external identity
        # ----------------------------------------------------

        identity = (
            decode_admin_token(
                raw_assertion
            )
        )

        # ----------------------------------------------------
        # Exact local administrator binding
        # ----------------------------------------------------

        admin = (
            await get_admin_for_identity(
                db,
                identity=identity,
            )
        )

        now = datetime.now(
            UTC
        )

        # ----------------------------------------------------
        # Normal session establishment does not fabricate MFA
        # assurance.
        # ----------------------------------------------------

        created = (
            await create_admin_session(
                db,
                admin=admin,
                authenticated_at=now,
                mfa_verified_at=None,
                phishing_resistant_verified_at=(
                    None
                ),
                auth_method=auth_method,
                ip_address=(
                    _client_ip(
                        request
                    )
                ),
                user_agent=(
                    _user_agent(
                        request
                    )
                ),
            )
        )

        # ----------------------------------------------------
        # Audit authentication
        # ----------------------------------------------------

        await record_audit_event(
            db,
            actor_type=(
                ActorType.ADMIN.value
            ),
            actor_id=str(
                admin.id
            ),
            action=(
                AuditAction
                .ADMIN_AUTH_SUCCEEDED
                .value
            ),
            metadata={
                "auth_method": (
                    auth_method
                ),
                "mfa_verified": False,
                "phishing_resistant_mfa": (
                    False
                ),
            },
            ip_address=_client_ip(
                request
            ),
            admin_session_id=(
                created.session.id
            ),
            request_id=_request_id(
                request
            ),
            user_agent=_user_agent(
                request
            ),
            outcome="success",
        )

        # ----------------------------------------------------
        # Audit session creation
        # ----------------------------------------------------

        await record_audit_event(
            db,
            actor_type=(
                ActorType.ADMIN.value
            ),
            actor_id=str(
                admin.id
            ),
            action=(
                AuditAction
                .ADMIN_SESSION_CREATED
                .value
            ),
            metadata={
                "auth_method": (
                    auth_method
                ),
            },
            ip_address=_client_ip(
                request
            ),
            admin_session_id=(
                created.session.id
            ),
            request_id=_request_id(
                request
            ),
            user_agent=_user_agent(
                request
            ),
            outcome="success",
        )

        await db.commit()

    except AdminAuthenticationError as exc:
        await db.rollback()

        await _record_denied_auth_event(
            db,
            request=request,
            action=(
                AuditAction
                .ADMIN_AUTH_DENIED
            ),
            reason=(
                "authentication_denied"
            ),
            admin=admin,
        )

        response_headers: (
            dict[str, str]
            | None
        ) = None

        if development_auth:
            response_headers = {
                "WWW-Authenticate": (
                    "Bearer"
                ),
            }

        raise HTTPException(
            status_code=(
                status
                .HTTP_401_UNAUTHORIZED
            ),
            detail=(
                "Invalid administrator "
                "authentication."
            ),
            headers=(
                response_headers
            ),
        ) from exc

    except AdminSessionError as exc:
        await db.rollback()

        await _record_denied_auth_event(
            db,
            request=request,
            action=(
                AuditAction
                .ADMIN_AUTH_DENIED
            ),
            reason=(
                "session_establishment_"
                "failed"
            ),
            admin=admin,
        )

        raise HTTPException(
            status_code=(
                status
                .HTTP_401_UNAUTHORIZED
            ),
            detail=(
                "Unable to establish "
                "administrator session."
            ),
        ) from exc

    if (
        admin is None
        or created is None
    ):
        raise RuntimeError(
            "Administrator session creation "
            "completed without required "
            "result state."
        )

    # --------------------------------------------------------
    # Browser credentials are issued only after commit.
    # --------------------------------------------------------

    _set_admin_cookies(
        response,
        created=created,
    )

    response.headers[
        "Cache-Control"
    ] = "no-store"

    return {
        "authenticated": True,
        "admin": (
            _admin_payload(
                admin
            )
        ),
        "expires_at": (
            created
            .session
            .expires_at
            .isoformat()
        ),
        "csrf_token": (
            created.csrf_token
        ),
    }


# ============================================================
# ADMINISTRATOR STEP-UP
# ============================================================


@router.post(
    "/step-up",
    status_code=status.HTTP_200_OK,
)
async def step_up_admin_session(
    request: Request,
    response: Response,
    db: DatabaseSession,
    admin_session_token: Annotated[
        str | None,
        Cookie(
            alias=(
                get_admin_session_cookie_name()
            ),
        ),
    ] = None,
    csrf_cookie: Annotated[
        str | None,
        Cookie(
            alias=(
                get_admin_csrf_cookie_name()
            ),
        ),
    ] = None,
    csrf_header: Annotated[
        str | None,
        Header(
            alias=(
                settings
                .admin_csrf_header_name
            ),
        ),
    ] = None,
    cloudflare_access_assertion: Annotated[
        str | None,
        Header(
            alias=(
                "Cf-Access-Jwt-Assertion"
            ),
        ),
    ] = None,
) -> dict[str, object]:
    """
    Upgrade an existing BAKABOOST administrator session after
    successful validation of the dedicated Cloudflare Access
    step-up application assertion.

    Security properties:

    - requires an existing valid local administrator session;
    - requires valid CSRF cookie/header binding;
    - requires the dedicated Cloudflare step-up audience;
    - immutable step-up subject must exactly match the current
      local administrator subject;
    - ordinary Cloudflare Access assertions are never accepted
      as step-up proof;
    - local MFA assurance timestamp is created only after this
      dedicated validation boundary succeeds;
    - phishing-resistant MFA is never fabricated;
    - both authentication and CSRF credentials rotate;
    - the same persistent session row is retained;
    - absolute session expiry is not extended;
    - database changes and audit events commit atomically;
    - replacement browser credentials are issued only after
      successful commit.

    The dedicated Cloudflare Access application/policy must
    itself enforce the required MFA ceremony.
    """

    if not admin_session_token:
        raise HTTPException(
            status_code=(
                status
                .HTTP_401_UNAUTHORIZED
            ),
            detail=(
                "Authentication required."
            ),
        )

    validated = None
    rotated: (
        CreatedAdminSession
        | None
    ) = None

    try:
        # ----------------------------------------------------
        # Resolve existing local administrator session.
        # ----------------------------------------------------
        #
        # Do not touch last_seen_at here before all step-up
        # validation succeeds. Rotation will update session
        # activity on the successful path.
        #

        validated = (
            await get_valid_admin_session(
                db,
                raw_token=(
                    admin_session_token
                ),
                touch=False,
            )
        )

        # ----------------------------------------------------
        # CSRF validation
        # ----------------------------------------------------

        validate_admin_session_csrf(
            validated.session,
            cookie_token=(
                csrf_cookie
            ),
            header_token=(
                csrf_header
            ),
        )

        # ----------------------------------------------------
        # Dedicated step-up assertion required.
        # ----------------------------------------------------

        raw_step_up_assertion: (
            str | None
        ) = None

        if isinstance(
            cloudflare_access_assertion,
            str,
        ):
            candidate = (
                cloudflare_access_assertion
                .strip()
            )

            if candidate:
                raw_step_up_assertion = (
                    candidate
                )

        if raw_step_up_assertion is None:
            raise AdminAuthenticationError(
                "Missing administrator "
                "step-up authentication."
            )

        # ----------------------------------------------------
        # Cryptographically validate only against dedicated
        # step-up audience.
        # ----------------------------------------------------

        step_up_identity = (
            decode_admin_step_up_token(
                raw_step_up_assertion
            )
        )

        # ----------------------------------------------------
        # Immutable identity binding.
        # ----------------------------------------------------
        #
        # A valid step-up assertion for another administrator
        # must never upgrade the current browser session.
        #

        current_subject = (
            validated
            .admin
            .auth_subject
        )

        if not isinstance(
            current_subject,
            str,
        ):
            raise (
                AdminAuthenticationError(
                    "Administrator identity "
                    "binding is invalid."
                )
            )

        normalized_current_subject = (
            current_subject.strip()
        )

        if (
            not normalized_current_subject
            or step_up_identity.subject
            != normalized_current_subject
        ):
            raise (
                AdminAuthenticationError(
                    "Administrator step-up "
                    "identity mismatch."
                )
            )

        # ----------------------------------------------------
        # Upgrade local assurance.
        # ----------------------------------------------------
        #
        # This local timestamp represents the successful
        # backend verification boundary of the dedicated
        # step-up assertion.
        #
        # It is deliberately NOT copied from JWT iat.
        #

        now = datetime.now(
            UTC
        )

        validated.session.authenticated_at = (
            now
        )

        validated.session.mfa_verified_at = (
            now
        )

        #
        # Independent MFA may include methods such as TOTP.
        # Therefore generic step-up success must not claim
        # phishing-resistant authentication.
        #
        validated.session.phishing_resistant_verified_at = (
            None
        )

        validated.session.auth_method = (
            "cloudflare_access_step_up"
        )

        # ----------------------------------------------------
        # Rotate both authentication and CSRF credentials.
        # ----------------------------------------------------

        rotated = (
            await rotate_admin_session(
                db,
                admin_session=(
                    validated.session
                ),
            )
        )

        # ----------------------------------------------------
        # Audit successful step-up.
        # ----------------------------------------------------

        await record_audit_event(
            db,
            actor_type=(
                ActorType.ADMIN.value
            ),
            actor_id=str(
                validated.admin.id
            ),
            action=(
                AuditAction
                .ADMIN_STEP_UP_SUCCEEDED
                .value
            ),
            metadata={
                "auth_method": (
                    "cloudflare_access_step_up"
                ),
                "mfa_verified": True,
                "phishing_resistant_mfa": (
                    False
                ),
            },
            ip_address=_client_ip(
                request
            ),
            admin_session_id=(
                validated.session.id
            ),
            request_id=_request_id(
                request
            ),
            user_agent=_user_agent(
                request
            ),
            outcome="success",
        )

        # ----------------------------------------------------
        # Audit credential rotation.
        # ----------------------------------------------------

        await record_audit_event(
            db,
            actor_type=(
                ActorType.ADMIN.value
            ),
            actor_id=str(
                validated.admin.id
            ),
            action=(
                AuditAction
                .ADMIN_SESSION_ROTATED
                .value
            ),
            metadata={
                "reason": (
                    "step_up"
                ),
            },
            ip_address=_client_ip(
                request
            ),
            admin_session_id=(
                validated.session.id
            ),
            request_id=_request_id(
                request
            ),
            user_agent=_user_agent(
                request
            ),
            outcome="success",
        )

        # ----------------------------------------------------
        # Assurance upgrade + token rotation + audit commit
        # atomically.
        # ----------------------------------------------------

        await db.commit()

    except InvalidAdminSessionError as exc:
        await db.rollback()

        if validated is not None:
            #
            # Base session validation already succeeded.
            # Therefore this is a CSRF validation failure.
            #
            await _record_denied_auth_event(
                db,
                request=request,
                action=(
                    AuditAction
                    .ADMIN_CSRF_DENIED
                ),
                reason=(
                    exc.reason
                    or "csrf_validation_failed"
                ),
                admin=validated.admin,
                admin_session_id=(
                    validated.session.id
                ),
            )

            raise HTTPException(
                status_code=(
                    status
                    .HTTP_403_FORBIDDEN
                ),
                detail=(
                    "Invalid request "
                    "verification."
                ),
            ) from exc

        if exc.requires_revocation:
            await (
                _persist_invalid_admin_session(
                    db,
                    request=request,
                    exc=exc,
                )
            )

        else:
            await _record_denied_auth_event(
                db,
                request=request,
                action=(
                    AuditAction
                    .ADMIN_AUTH_DENIED
                ),
                reason=(
                    exc.reason
                    or "invalid_admin_session"
                ),
            )

        raise HTTPException(
            status_code=(
                status
                .HTTP_401_UNAUTHORIZED
            ),
            detail=(
                "Authentication required."
            ),
        ) from exc

    except AdminAuthenticationError as exc:
        await db.rollback()

        reason = (
            "step_up_authentication_denied"
        )

        #
        # Record a more useful safe reason when the assertion
        # was entirely absent. Never record the assertion.
        #
        if (
            cloudflare_access_assertion
            is None
            or (
                isinstance(
                    cloudflare_access_assertion,
                    str,
                )
                and not (
                    cloudflare_access_assertion
                    .strip()
                )
            )
        ):
            reason = (
                "missing_cloudflare_"
                "step_up_assertion"
            )

        elif (
            validated is not None
            and "mismatch"
            in str(exc).lower()
        ):
            reason = (
                "step_up_subject_mismatch"
            )

        await _record_denied_auth_event(
            db,
            request=request,
            action=(
                AuditAction
                .ADMIN_STEP_UP_DENIED
            ),
            reason=reason,
            admin=(
                validated.admin
                if validated
                is not None
                else None
            ),
            admin_session_id=(
                validated.session.id
                if validated
                is not None
                else None
            ),
        )

        raise HTTPException(
            status_code=(
                status
                .HTTP_403_FORBIDDEN
            ),
            detail=(
                "Additional administrator "
                "authentication failed."
            ),
        ) from exc

    except AdminSessionError as exc:
        await db.rollback()

        await _record_denied_auth_event(
            db,
            request=request,
            action=(
                AuditAction
                .ADMIN_STEP_UP_DENIED
            ),
            reason=(
                "step_up_session_rotation_"
                "failed"
            ),
            admin=(
                validated.admin
                if validated
                is not None
                else None
            ),
            admin_session_id=(
                validated.session.id
                if validated
                is not None
                else None
            ),
        )

        raise HTTPException(
            status_code=(
                status
                .HTTP_403_FORBIDDEN
            ),
            detail=(
                "Unable to complete "
                "administrator step-up."
            ),
        ) from exc

    # --------------------------------------------------------
    # Successful path invariants
    # --------------------------------------------------------

    if (
        validated is None
        or rotated is None
    ):
        raise RuntimeError(
            "Administrator step-up completed "
            "without required result state."
        )

    # --------------------------------------------------------
    # New credentials are exposed only after the transaction
    # has committed successfully.
    # --------------------------------------------------------

    _set_admin_cookies(
        response,
        created=rotated,
    )

    response.headers[
        "Cache-Control"
    ] = "no-store"

    return {
        "authenticated": True,
        "step_up_verified": True,
        "mfa_verified": True,
        "phishing_resistant_mfa": (
            False
        ),
        "admin": (
            _admin_payload(
                validated.admin
            )
        ),
        "expires_at": (
            rotated
            .session
            .expires_at
            .isoformat()
        ),
        "csrf_token": (
            rotated.csrf_token
        ),
    }


# ============================================================
# CURRENT ADMIN SESSION
# ============================================================


@router.get(
    "/session"
)
async def read_admin_session(
    request: Request,
    response: Response,
    db: DatabaseSession,
    admin_session_token: Annotated[
        str | None,
        Cookie(
            alias=(
                get_admin_session_cookie_name()
            ),
        ),
    ] = None,
) -> dict[str, object]:
    """
    Validate the existing server-managed administrator
    session and issue fresh CSRF material.

    The raw authentication credential remains HttpOnly and is
    never returned to frontend JavaScript.
    """

    if not admin_session_token:
        raise HTTPException(
            status_code=(
                status
                .HTTP_401_UNAUTHORIZED
            ),
            detail=(
                "Authentication required."
            ),
        )

    try:
        validated = (
            await get_valid_admin_session(
                db,
                raw_token=(
                    admin_session_token
                ),
            )
        )

        csrf_token = (
            await rotate_admin_csrf_token(
                db,
                admin_session=(
                    validated.session
                ),
            )
        )

        await record_audit_event(
            db,
            actor_type=(
                ActorType.ADMIN.value
            ),
            actor_id=str(
                validated.admin.id
            ),
            action=(
                AuditAction
                .ADMIN_SESSION_RESTORED
                .value
            ),
            metadata={},
            ip_address=_client_ip(
                request
            ),
            admin_session_id=(
                validated.session.id
            ),
            request_id=_request_id(
                request
            ),
            user_agent=_user_agent(
                request
            ),
            outcome="success",
        )

        await db.commit()

    except InvalidAdminSessionError as exc:
        await db.rollback()

        if exc.requires_revocation:
            await (
                _persist_invalid_admin_session(
                    db,
                    request=request,
                    exc=exc,
                )
            )

        else:
            await _record_denied_auth_event(
                db,
                request=request,
                action=(
                    AuditAction
                    .ADMIN_AUTH_DENIED
                ),
                reason=(
                    exc.reason
                    or "invalid_admin_session"
                ),
            )

        raise HTTPException(
            status_code=(
                status
                .HTTP_401_UNAUTHORIZED
            ),
            detail=(
                "Authentication required."
            ),
        ) from exc

    secure = bool(
        settings.cookie_secure
    )

    if _is_production():
        secure = True

    response.set_cookie(
        key=(
            get_admin_csrf_cookie_name()
        ),
        value=csrf_token,
        max_age=(
            settings
            .admin_session_absolute_lifetime_seconds
        ),
        httponly=False,
        secure=secure,
        samesite="lax",
        path="/",
    )

    response.headers[
        "Cache-Control"
    ] = "no-store"

    return {
        "authenticated": True,
        "admin": (
            _admin_payload(
                validated.admin
            )
        ),
        "expires_at": (
            validated
            .session
            .expires_at
            .isoformat()
        ),
        "csrf_token": (
            csrf_token
        ),
    }


# ============================================================
# LOGOUT
# ============================================================


@router.delete(
    "/session",
    status_code=(
        status.HTTP_204_NO_CONTENT
    ),
)
async def destroy_admin_session(
    request: Request,
    response: Response,
    db: DatabaseSession,
    admin_session_token: Annotated[
        str | None,
        Cookie(
            alias=(
                get_admin_session_cookie_name()
            ),
        ),
    ] = None,
    csrf_cookie: Annotated[
        str | None,
        Cookie(
            alias=(
                get_admin_csrf_cookie_name()
            ),
        ),
    ] = None,
    csrf_header: Annotated[
        str | None,
        Header(
            alias=(
                settings
                .admin_csrf_header_name
            ),
        ),
    ] = None,
) -> Response:
    """
    Revoke the current administrator session.

    Logout is CSRF-protected when an authenticated session
    exists.
    """

    if not admin_session_token:
        _clear_admin_cookies(
            response
        )

        response.status_code = (
            status
            .HTTP_204_NO_CONTENT
        )

        return response

    validated = None

    try:
        validated = (
            await get_valid_admin_session(
                db,
                raw_token=(
                    admin_session_token
                ),
                touch=False,
            )
        )

        validate_admin_session_csrf(
            validated.session,
            cookie_token=(
                csrf_cookie
            ),
            header_token=(
                csrf_header
            ),
        )

        await revoke_admin_session(
            db,
            admin_session=(
                validated.session
            ),
            reason="logout",
        )

        await record_audit_event(
            db,
            actor_type=(
                ActorType.ADMIN.value
            ),
            actor_id=str(
                validated.admin.id
            ),
            action=(
                AuditAction
                .ADMIN_SESSION_REVOKED
                .value
            ),
            metadata={
                "reason": "logout",
            },
            ip_address=_client_ip(
                request
            ),
            admin_session_id=(
                validated.session.id
            ),
            request_id=_request_id(
                request
            ),
            user_agent=_user_agent(
                request
            ),
            outcome="success",
        )

        await db.commit()

    except InvalidAdminSessionError as exc:
        await db.rollback()

        if validated is not None:
            await _record_denied_auth_event(
                db,
                request=request,
                action=(
                    AuditAction
                    .ADMIN_CSRF_DENIED
                ),
                reason=(
                    exc.reason
                    or "csrf_validation_failed"
                ),
                admin=(
                    validated.admin
                ),
                admin_session_id=(
                    validated.session.id
                ),
            )

        elif exc.requires_revocation:
            await (
                _persist_invalid_admin_session(
                    db,
                    request=request,
                    exc=exc,
                )
            )

        else:
            await _record_denied_auth_event(
                db,
                request=request,
                action=(
                    AuditAction
                    .ADMIN_AUTH_DENIED
                ),
                reason=(
                    exc.reason
                    or "invalid_admin_session"
                ),
            )

        raise HTTPException(
            status_code=(
                status
                .HTTP_403_FORBIDDEN
            ),
            detail=(
                "Invalid request "
                "verification."
            ),
        ) from exc

    except AdminSessionError as exc:
        await db.rollback()

        await _record_denied_auth_event(
            db,
            request=request,
            action=(
                AuditAction
                .ADMIN_AUTH_DENIED
            ),
            reason=(
                "session_revocation_failed"
            ),
            admin=(
                validated.admin
                if validated
                is not None
                else None
            ),
            admin_session_id=(
                validated.session.id
                if validated
                is not None
                else None
            ),
        )

        raise HTTPException(
            status_code=(
                status
                .HTTP_403_FORBIDDEN
            ),
            detail=(
                "Invalid request "
                "verification."
            ),
        ) from exc

    _clear_admin_cookies(
        response
    )

    response.status_code = (
        status.HTTP_204_NO_CONTENT
    )

    return response