from __future__ import annotations

from collections.abc import Mapping
from datetime import UTC, datetime
from typing import Annotated, Any
from uuid import UUID

from fastapi import (
    APIRouter,
    Cookie,
    Depends,
    Header,
    HTTPException,
    Request,
    Response,
    status,
)
from fastapi.security import (
    HTTPAuthorizationCredentials,
    HTTPBearer,
)
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.constants import (
    ActorType,
    AuditAction,
)
from app.db.models.admin import Admin
from app.db.session import get_db_session
from app.services.admin.auth import (
    AdminAuthenticationError,
    AdminMFARequiredError,
    AdminReauthenticationRequiredError,
    admin_token_has_mfa,
    admin_token_has_phishing_resistant_mfa,
    decode_admin_token,
    get_admin_authenticated_at,
    get_admin_for_identity,
    require_admin_mfa,
    require_recent_admin_authentication,
)
from app.services.admin.session_service import (
    AdminSessionError,
    CreatedAdminSession,
    InvalidAdminSessionError,
    create_admin_session,
    get_admin_csrf_cookie_name,
    get_admin_session_cookie_name,
    get_valid_admin_session,
    revoke_admin_session,
    revoke_admin_session_by_id,
    rotate_admin_csrf_token,
    validate_admin_session_csrf,
)
from app.services.audit.service import (
    record_audit_event,
)

# ============================================================
# ROUTER
# ============================================================


router = APIRouter(
    prefix="/auth",
    tags=["admin-auth"],
)


# ============================================================
# FASTAPI DEPENDENCIES
# ============================================================


_bearer = HTTPBearer(
    auto_error=False,
)

BearerCredentials = Annotated[
    HTTPAuthorizationCredentials | None,
    Depends(_bearer),
]

DatabaseSession = Annotated[
    AsyncSession,
    Depends(get_db_session),
]


# ============================================================
# HELPERS
# ============================================================


def _is_production() -> bool:
    return (
        str(settings.app_environment)
        .strip()
        .lower()
        == "production"
    )


def _development_step_up_bypass_enabled() -> bool:
    """
    Temporary development-only compatibility.

    Production can never use this bypass.
    """

    return (
        not _is_production()
        and not settings.admin_auth_required_mfa
    )


def _client_ip(
    request: Request,
) -> str | None:
    """
    Use the direct socket peer address.

    X-Forwarded-For is intentionally not trusted here.
    Production proxy trust must be configured explicitly at
    the deployment boundary.
    """

    if request.client is None:
        return None

    return request.client.host


def _request_id(
    request: Request,
) -> str | None:
    """
    Return the trusted request correlation ID generated by
    RequestContextMiddleware.

    Do not accept a client-supplied request ID here.
    """

    value = getattr(
        request.state,
        "request_id",
        None,
    )

    if not isinstance(value, str):
        return None

    normalized = value.strip()

    return normalized or None


def _user_agent(
    request: Request,
) -> str | None:
    return request.headers.get(
        "user-agent"
    )


async def _record_denied_auth_event(
    db: AsyncSession,
    *,
    request: Request,
    action: AuditAction,
    reason: str,
    admin: Admin | None = None,
    admin_session_id: UUID | None = None,
    metadata: Mapping[str, Any] | None = None,
) -> None:
    """
    Persist an authentication/security denial after the
    caller has rolled back the failed protected operation.

    Authentication credentials, session tokens, CSRF tokens,
    OIDC claims and other secrets must never be placed in
    audit metadata.
    """

    event_metadata: dict[str, Any] = {
        "reason": reason,
    }

    if metadata is not None:
        event_metadata.update(
            dict(metadata)
        )

    await record_audit_event(
        db,
        actor_type=(
            ActorType.ADMIN.value
            if admin is not None
            else ActorType.SYSTEM.value
        ),
        actor_id=(
            str(admin.id)
            if admin is not None
            else None
        ),
        action=action.value,
        metadata=event_metadata,
        ip_address=_client_ip(
            request
        ),
        admin_session_id=admin_session_id,
        request_id=_request_id(
            request
        ),
        user_agent=_user_agent(
            request
        ),
        outcome="failure",
    )

    await db.commit()


async def _persist_invalid_admin_session(
    db: AsyncSession,
    *,
    request: Request,
    exc: InvalidAdminSessionError,
) -> None:
    """
    Persist automatic administrator-session invalidation after
    the failed validation transaction has been rolled back.

    Revocation and the corresponding audit event are committed
    atomically.

    Only safe persistent identifiers and reason codes from the
    validation exception are used. Raw session credentials are
    never logged or persisted here.
    """

    if not exc.requires_revocation:
        return

    if (
        exc.admin_id is None
        or exc.admin_session_id is None
    ):
        return

    reason = (
        exc.reason
        or "security_state_changed"
    )

    await revoke_admin_session_by_id(
        db,
        admin_session_id=(
            exc.admin_session_id
        ),
        admin_id=exc.admin_id,
        reason=reason,
    )

    if reason == "absolute_expiry":
        action = (
            AuditAction.ADMIN_SESSION_EXPIRED
        )

    elif reason == "idle_timeout":
        action = (
            AuditAction.ADMIN_SESSION_IDLE_EXPIRED
        )

    else:
        action = (
            AuditAction
            .ADMIN_SESSION_SECURITY_INVALIDATED
        )

    await record_audit_event(
        db,
        actor_type=ActorType.ADMIN.value,
        actor_id=str(
            exc.admin_id
        ),
        action=action.value,
        metadata={
            "reason": reason,
        },
        ip_address=_client_ip(
            request
        ),
        admin_session_id=(
            exc.admin_session_id
        ),
        request_id=_request_id(
            request
        ),
        user_agent=_user_agent(
            request
        ),
        outcome="failure",
    )

    await db.commit()


def _set_admin_cookies(
    response: Response,
    *,
    created: CreatedAdminSession,
) -> None:
    """
    Set the server-managed authentication cookie and the
    separate browser-readable CSRF cookie.
    """

    secure = bool(settings.cookie_secure)

    if _is_production():
        secure = True

    session_cookie_name = (
        get_admin_session_cookie_name()
    )

    csrf_cookie_name = (
        get_admin_csrf_cookie_name()
    )

    # --------------------------------------------------------
    # Authentication credential
    # --------------------------------------------------------
    #
    # Raw administrator session token:
    #
    # - HttpOnly
    # - Secure in production
    # - SameSite=Lax
    # - Path=/
    # - no Domain
    #
    # The raw value is never stored in PostgreSQL.
    #
    response.set_cookie(
        key=session_cookie_name,
        value=created.raw_token,
        max_age=(
            settings
            .admin_session_absolute_lifetime_seconds
        ),
        httponly=True,
        secure=secure,
        samesite="lax",
        path="/",
    )

    # --------------------------------------------------------
    # CSRF credential
    # --------------------------------------------------------
    #
    # This value is intentionally readable by frontend
    # JavaScript because the frontend must echo it in the
    # X-Admin-CSRF-Token header.
    #
    # It is NOT an authentication credential.
    #
    response.set_cookie(
        key=csrf_cookie_name,
        value=created.csrf_token,
        max_age=(
            settings
            .admin_session_absolute_lifetime_seconds
        ),
        httponly=False,
        secure=secure,
        samesite="lax",
        path="/",
    )


def _clear_admin_cookies(
    response: Response,
) -> None:
    """
    Remove both administrator browser cookies.
    """

    secure = bool(settings.cookie_secure)

    if _is_production():
        secure = True

    response.delete_cookie(
        key=get_admin_session_cookie_name(),
        path="/",
        secure=secure,
        httponly=True,
        samesite="lax",
    )

    response.delete_cookie(
        key=get_admin_csrf_cookie_name(),
        path="/",
        secure=secure,
        httponly=False,
        samesite="lax",
    )


def _admin_payload(
    admin: Admin,
) -> dict[str, object]:
    """
    Safe administrator representation returned to the
    authenticated frontend.

    Do not expose auth_subject or authentication secrets.
    """

    return {
        "id": str(admin.id),
        "email": admin.email,
        "display_name": admin.display_name,
        "role": admin.role.value,
    }


# ============================================================
# CREATE SERVER-MANAGED SESSION
# ============================================================


@router.post(
    "/session",
    status_code=status.HTTP_201_CREATED,
)
async def establish_admin_session(
    request: Request,
    response: Response,
    credentials: BearerCredentials,
    db: DatabaseSession,
) -> dict[str, object]:
    """
    Exchange a valid external OIDC access token for a
    BAKABOOST server-managed administrator session.

    Successful external authentication alone does NOT grant
    administrator access.

    The immutable external subject must also correspond to an
    explicitly provisioned and active local Admin row.
    """

    # --------------------------------------------------------
    # Missing bearer credential
    # --------------------------------------------------------

    if credentials is None:
        await _record_denied_auth_event(
            db,
            request=request,
            action=AuditAction.ADMIN_AUTH_DENIED,
            reason="missing_bearer_credentials",
        )

        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required.",
            headers={
                "WWW-Authenticate": "Bearer",
            },
        )

    admin: Admin | None = None
    created: CreatedAdminSession | None = None

    try:
        # ----------------------------------------------------
        # Verify external identity
        # ----------------------------------------------------

        identity = decode_admin_token(
            credentials.credentials
        )

        development_bypass = (
            _development_step_up_bypass_enabled()
        )

        # ----------------------------------------------------
        # MFA policy
        # ----------------------------------------------------

        if not development_bypass:
            require_admin_mfa(
                identity
            )

            #
            # Do not silently convert a very old IdP session
            # into a fresh BAKABOOST administrator session.
            #
            require_recent_admin_authentication(
                identity
            )

        # ----------------------------------------------------
        # Exact local administrator binding
        # ----------------------------------------------------

        admin = await get_admin_for_identity(
            db,
            identity=identity,
        )

        # ----------------------------------------------------
        # Authentication timestamp
        # ----------------------------------------------------

        authenticated_at = (
            get_admin_authenticated_at(
                identity,
                require_auth_time=(
                    not development_bypass
                ),
            )
        )

        now = datetime.now(UTC)

        # ----------------------------------------------------
        # Authentication assurance snapshot
        # ----------------------------------------------------

        mfa_verified_at = (
            now
            if admin_token_has_mfa(
                identity.claims
            )
            else None
        )

        phishing_resistant_verified_at = (
            now
            if (
                admin_token_has_phishing_resistant_mfa(
                    identity.claims
                )
            )
            else None
        )

        # ----------------------------------------------------
        # Create server-side session
        # ----------------------------------------------------

        created = await create_admin_session(
            db,
            admin=admin,
            authenticated_at=authenticated_at,
            mfa_verified_at=mfa_verified_at,
            phishing_resistant_verified_at=(
                phishing_resistant_verified_at
            ),
            auth_method="oidc",
            ip_address=_client_ip(
                request
            ),
            user_agent=_user_agent(
                request
            ),
        )

        # ----------------------------------------------------
        # Audit successful authentication
        # ----------------------------------------------------

        await record_audit_event(
            db,
            actor_type=ActorType.ADMIN.value,
            actor_id=str(admin.id),
            action=(
                AuditAction
                .ADMIN_AUTH_SUCCEEDED
                .value
            ),
            metadata={
                "auth_method": "oidc",
                "mfa_verified": (
                    mfa_verified_at is not None
                ),
                "phishing_resistant_mfa": (
                    phishing_resistant_verified_at
                    is not None
                ),
            },
            ip_address=_client_ip(
                request
            ),
            admin_session_id=(
                created.session.id
            ),
            request_id=_request_id(
                request
            ),
            user_agent=_user_agent(
                request
            ),
            outcome="success",
        )

        # ----------------------------------------------------
        # Audit session creation
        # ----------------------------------------------------

        await record_audit_event(
            db,
            actor_type=ActorType.ADMIN.value,
            actor_id=str(admin.id),
            action=(
                AuditAction
                .ADMIN_SESSION_CREATED
                .value
            ),
            metadata={
                "auth_method": "oidc",
            },
            ip_address=_client_ip(
                request
            ),
            admin_session_id=(
                created.session.id
            ),
            request_id=_request_id(
                request
            ),
            user_agent=_user_agent(
                request
            ),
            outcome="success",
        )

        # ----------------------------------------------------
        # Persist session + successful audit events atomically
        # ----------------------------------------------------

        await db.commit()

    except AdminMFARequiredError as exc:
        await db.rollback()

        await _record_denied_auth_event(
            db,
            request=request,
            action=AuditAction.ADMIN_MFA_REQUIRED,
            reason="mfa_required",
        )

        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=(
                "Additional administrator "
                "authentication required."
            ),
        ) from exc

    except AdminReauthenticationRequiredError as exc:
        await db.rollback()

        await _record_denied_auth_event(
            db,
            request=request,
            action=(
                AuditAction.ADMIN_REAUTH_REQUIRED
            ),
            reason="reauthentication_required",
        )

        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=(
                "Administrator reauthentication required."
            ),
        ) from exc

    except AdminAuthenticationError as exc:
        await db.rollback()

        await _record_denied_auth_event(
            db,
            request=request,
            action=AuditAction.ADMIN_AUTH_DENIED,
            reason="authentication_denied",
            admin=admin,
        )

        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=(
                "Invalid administrator authentication."
            ),
            headers={
                "WWW-Authenticate": "Bearer",
            },
        ) from exc

    except AdminSessionError as exc:
        await db.rollback()

        await _record_denied_auth_event(
            db,
            request=request,
            action=AuditAction.ADMIN_AUTH_DENIED,
            reason="session_establishment_failed",
            admin=admin,
        )

        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=(
                "Unable to establish "
                "administrator session."
            ),
        ) from exc

    # --------------------------------------------------------
    # Successful path invariants
    # --------------------------------------------------------

    if admin is None or created is None:
        raise RuntimeError(
            "Administrator session creation completed "
            "without required result state."
        )

    # --------------------------------------------------------
    # Only set cookies after the DB transaction succeeds
    # --------------------------------------------------------

    _set_admin_cookies(
        response,
        created=created,
    )

    response.headers[
        "Cache-Control"
    ] = "no-store"

    return {
        "authenticated": True,
        "admin": _admin_payload(
            admin
        ),
        "expires_at": (
            created.session.expires_at.isoformat()
        ),
        "csrf_token": created.csrf_token,
    }


# ============================================================
# CURRENT ADMIN SESSION
# ============================================================


@router.get(
    "/session"
)
async def read_admin_session(
    request: Request,
    response: Response,
    db: DatabaseSession,
    admin_session_token: Annotated[
        str | None,
        Cookie(
            alias=get_admin_session_cookie_name(),
        ),
    ] = None,
) -> dict[str, object]:
    """
    Validate the existing server-managed administrator
    session and issue fresh CSRF material.

    The raw authentication credential remains HttpOnly and is
    never returned to frontend JavaScript.
    """

    if not admin_session_token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required.",
        )

    try:
        validated = await get_valid_admin_session(
            db,
            raw_token=admin_session_token,
        )

        csrf_token = await rotate_admin_csrf_token(
            db,
            admin_session=validated.session,
        )

        # ----------------------------------------------------
        # Audit successful session restoration
        # ----------------------------------------------------

        await record_audit_event(
            db,
            actor_type=ActorType.ADMIN.value,
            actor_id=str(
                validated.admin.id
            ),
            action=(
                AuditAction
                .ADMIN_SESSION_RESTORED
                .value
            ),
            metadata={},
            ip_address=_client_ip(
                request
            ),
            admin_session_id=(
                validated.session.id
            ),
            request_id=_request_id(
                request
            ),
            user_agent=_user_agent(
                request
            ),
            outcome="success",
        )

        await db.commit()

    except InvalidAdminSessionError as exc:
        await db.rollback()

        if exc.requires_revocation:
            await _persist_invalid_admin_session(
                db,
                request=request,
                exc=exc,
            )

        else:
            await _record_denied_auth_event(
                db,
                request=request,
                action=(
                    AuditAction.ADMIN_AUTH_DENIED
                ),
                reason=(
                    exc.reason
                    or "invalid_admin_session"
                ),
            )

        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required.",
        ) from exc

    # --------------------------------------------------------
    # Refresh browser-readable CSRF material
    # --------------------------------------------------------

    secure = bool(settings.cookie_secure)

    if _is_production():
        secure = True

    response.set_cookie(
        key=get_admin_csrf_cookie_name(),
        value=csrf_token,
        max_age=(
            settings
            .admin_session_absolute_lifetime_seconds
        ),
        httponly=False,
        secure=secure,
        samesite="lax",
        path="/",
    )

    response.headers[
        "Cache-Control"
    ] = "no-store"

    return {
        "authenticated": True,
        "admin": _admin_payload(
            validated.admin
        ),
        "expires_at": (
            validated.session.expires_at.isoformat()
        ),
        "csrf_token": csrf_token,
    }


# ============================================================
# LOGOUT
# ============================================================


@router.delete(
    "/session",
    status_code=status.HTTP_204_NO_CONTENT,
)
async def destroy_admin_session(
    request: Request,
    response: Response,
    db: DatabaseSession,
    admin_session_token: Annotated[
        str | None,
        Cookie(
            alias=get_admin_session_cookie_name(),
        ),
    ] = None,
    csrf_cookie: Annotated[
        str | None,
        Cookie(
            alias=get_admin_csrf_cookie_name(),
        ),
    ] = None,
    csrf_header: Annotated[
        str | None,
        Header(
            alias=settings.admin_csrf_header_name,
        ),
    ] = None,
) -> Response:
    """
    Revoke the current administrator session.

    Logout is CSRF-protected when an authenticated session
    exists.
    """

    # --------------------------------------------------------
    # No browser session
    # --------------------------------------------------------
    #
    # Treat logout without a session as idempotent.
    #
    if not admin_session_token:
        _clear_admin_cookies(
            response
        )

        response.status_code = (
            status.HTTP_204_NO_CONTENT
        )

        return response

    validated = None

    try:
        # ----------------------------------------------------
        # Resolve current session
        # ----------------------------------------------------

        validated = await get_valid_admin_session(
            db,
            raw_token=admin_session_token,
            touch=False,
        )

        # ----------------------------------------------------
        # CSRF validation
        # ----------------------------------------------------

        validate_admin_session_csrf(
            validated.session,
            cookie_token=csrf_cookie,
            header_token=csrf_header,
        )

        # ----------------------------------------------------
        # Server-side revocation
        # ----------------------------------------------------

        await revoke_admin_session(
            db,
            admin_session=validated.session,
            reason="logout",
        )

        # ----------------------------------------------------
        # Audit revocation in the same transaction
        # ----------------------------------------------------

        await record_audit_event(
            db,
            actor_type=ActorType.ADMIN.value,
            actor_id=str(
                validated.admin.id
            ),
            action=(
                AuditAction
                .ADMIN_SESSION_REVOKED
                .value
            ),
            metadata={
                "reason": "logout",
            },
            ip_address=_client_ip(
                request
            ),
            admin_session_id=(
                validated.session.id
            ),
            request_id=_request_id(
                request
            ),
            user_agent=_user_agent(
                request
            ),
            outcome="success",
        )

        await db.commit()

    except InvalidAdminSessionError as exc:
        await db.rollback()

        if validated is not None:
            #
            # Session validation succeeded. Therefore this
            # InvalidAdminSessionError came from the later
            # CSRF validation step.
            #
            await _record_denied_auth_event(
                db,
                request=request,
                action=(
                    AuditAction.ADMIN_CSRF_DENIED
                ),
                reason=(
                    exc.reason
                    or "csrf_validation_failed"
                ),
                admin=validated.admin,
                admin_session_id=(
                    validated.session.id
                ),
            )

        elif exc.requires_revocation:
            #
            # Validation reached a persistent session and
            # detected expiry/security invalidation.
            #
            await _persist_invalid_admin_session(
                db,
                request=request,
                exc=exc,
            )

        else:
            #
            # Unknown or already-revoked session credential.
            #
            await _record_denied_auth_event(
                db,
                request=request,
                action=(
                    AuditAction.ADMIN_AUTH_DENIED
                ),
                reason=(
                    exc.reason
                    or "invalid_admin_session"
                ),
            )

        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid request verification.",
        ) from exc

    except AdminSessionError as exc:
        await db.rollback()

        await _record_denied_auth_event(
            db,
            request=request,
            action=AuditAction.ADMIN_AUTH_DENIED,
            reason="session_revocation_failed",
            admin=(
                validated.admin
                if validated is not None
                else None
            ),
            admin_session_id=(
                validated.session.id
                if validated is not None
                else None
            ),
        )

        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid request verification.",
        ) from exc

    # --------------------------------------------------------
    # Remove browser credentials
    # --------------------------------------------------------

    _clear_admin_cookies(
        response
    )

    response.status_code = (
        status.HTTP_204_NO_CONTENT
    )

    return response